#include "Fixed.hpp"

int	main(void)
{
	// Fixed	a;
	// Fixed const	b( Fixed( 5.05f ) * Fixed( 2 ) );

	// std::cout << a << std::endl;
	// std::cout << a << std::endl;
	// std::cout << a << std::endl;
	// std::cout << a++ << std::endl;
	// std::cout << a << std::endl;
	
	// std::cout << b << std::endl;

	// std::cout << Fixed::max( a, b ) << std::endl;


	Fixed	a;
	Fixed	b( 10 );
	Fixed	c( -42.42f );
	Fixed	d( b );

	a = Fixed( 1234.4321f );

	std::cout << "a is " << a << std::endl;
	std::cout << "b is " << b << std::endl;
	std::cout << "c is " << c << std::endl;
	std::cout << "d is " << d << std::endl;

	std::cout << "a is " << a.toInt() << " as integer" << std::endl;
	std::cout << "b is " << b.toInt() << " as integer" << std::endl;
	std::cout << "c is " << c.toInt() << " as integer" << std::endl;
	std::cout << "d is " << d.toInt() << " as integer" << std::endl;

	std::cout << "a is " << a.toFloat() << " as float" << std::endl;
	std::cout << "b is " << b.toFloat() << " as float" << std::endl;
	std::cout << "c is " << c.toFloat() << " as float" << std::endl;
	std::cout << "d is " << d.toFloat() << " as float" << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;
	
	LOG("+ overload opertation");
	std::cout << "a + a = " << a << " + " << a << " = "<< a.toFloat() + a.toFloat() << std::endl;
	std::cout << "a + b = " << a << " + " << b << " = "<< a.toFloat() + b.toFloat() << std::endl;
	std::cout << "a + c = " << a << " + " << c << " = "<< a.toFloat() + c.toFloat() << std::endl;
	std::cout << "a + d = " << a << " + " << d << " = "<< a.toFloat() + d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b + a = " << b << " + " << a << " = "<< b.toFloat() + a.toFloat() << std::endl;
	std::cout << "b + b = " << b << " + " << b << " = "<< b.toFloat() + b.toFloat() << std::endl;
	std::cout << "b + c = " << b << " + " << c << " = "<< b.toFloat() + c.toFloat() << std::endl;
	std::cout << "b + d = " << b << " + " << d << " = "<< b.toFloat() + d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c + a = " << c << " + " << a << " = "<< c.toFloat() + a.toFloat() << std::endl;
	std::cout << "c + b = " << c << " + " << b << " = "<< c.toFloat() + b.toFloat() << std::endl;
	std::cout << "c + c = " << c << " + " << c << " = "<< c.toFloat() + c.toFloat() << std::endl;
	std::cout << "c + d = " << c << " + " << d << " = "<< c.toFloat() + d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d + a = " << d << " + " << a << " = "<< d.toFloat() + a.toFloat() << std::endl;
	std::cout << "d + b = " << d << " + " << b << " = "<< d.toFloat() + b.toFloat() << std::endl;
	std::cout << "d + c = " << d << " + " << c << " = "<< d.toFloat() + c.toFloat() << std::endl;
	std::cout << "d + d = " << d << " + " << d << " = "<< d.toFloat() + d.toFloat() << std::endl;
	std::cout << "+a = " << " + " << a << " = "<< (+a.toFloat()) << std::endl;
	std::cout << "+b = " << " + " << b << " = "<< (+b.toFloat()) << std::endl;
	std::cout << "+c = " << " + " << c << " = "<< (+c.toFloat()) << std::endl;
	std::cout << "+d = " << " + " << d << " = "<< (+d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("- overload opertation");
	std::cout << "a - a = " << a << " - " << a << " = "<< a.toFloat() - a.toFloat() << std::endl;
	std::cout << "a - b = " << a << " - " << b << " = "<< a.toFloat() - b.toFloat() << std::endl;
	std::cout << "a - c = " << a << " - " << c << " = "<< a.toFloat() - c.toFloat() << std::endl;
	std::cout << "a - d = " << a << " - " << d << " = "<< a.toFloat() - d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b - a = " << b << " - " << a << " = "<< b.toFloat() - a.toFloat() << std::endl;
	std::cout << "b - b = " << b << " - " << b << " = "<< b.toFloat() - b.toFloat() << std::endl;
	std::cout << "b - c = " << b << " - " << c << " = "<< b.toFloat() - c.toFloat() << std::endl;
	std::cout << "b - d = " << b << " - " << d << " = "<< b.toFloat() - d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c - a = " << c << " - " << a << " = "<< c.toFloat() - a.toFloat() << std::endl;
	std::cout << "c - b = " << c << " - " << b << " = "<< c.toFloat() - b.toFloat() << std::endl;
	std::cout << "c - c = " << c << " - " << c << " = "<< c.toFloat() - c.toFloat() << std::endl;
	std::cout << "c - d = " << c << " - " << d << " = "<< c.toFloat() - d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d - a = " << d << " - " << a << " = "<< d.toFloat() - a.toFloat() << std::endl;
	std::cout << "d - b = " << d << " - " << b << " = "<< d.toFloat() - b.toFloat() << std::endl;
	std::cout << "d - c = " << d << " - " << c << " = "<< d.toFloat() - c.toFloat() << std::endl;
	std::cout << "d - d = " << d << " - " << d << " = "<< d.toFloat() - d.toFloat() << std::endl;
	std::cout << "-a = " << " - " << a << " = "<< (-a.toFloat()) << std::endl;
	std::cout << "-b = " << " - " << b << " = "<< (-b.toFloat()) << std::endl;
	std::cout << "-c = " << " - " << c << " = "<< (-c.toFloat()) << std::endl;
	std::cout << "-d = " << " - " << d << " = "<< (-d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("* overload opertation");
	std::cout << "a * a = " << a << " * " << a << " = "<< a.toFloat() * a.toFloat() << std::endl;
	std::cout << "a * b = " << a << " * " << b << " = "<< a.toFloat() * b.toFloat() << std::endl;
	std::cout << "a * c = " << a << " * " << c << " = "<< a.toFloat() * c.toFloat() << std::endl;
	std::cout << "a * d = " << a << " * " << d << " = "<< a.toFloat() * d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b * a = " << b << " * " << a << " = "<< b.toFloat() * a.toFloat() << std::endl;
	std::cout << "b * b = " << b << " * " << b << " = "<< b.toFloat() * b.toFloat() << std::endl;
	std::cout << "b * c = " << b << " * " << c << " = "<< b.toFloat() * c.toFloat() << std::endl;
	std::cout << "b * d = " << b << " * " << d << " = "<< b.toFloat() * d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c * a = " << c << " * " << a << " = "<< c.toFloat() * a.toFloat() << std::endl;
	std::cout << "c * b = " << c << " * " << b << " = "<< c.toFloat() * b.toFloat() << std::endl;
	std::cout << "c * c = " << c << " * " << c << " = "<< c.toFloat() * c.toFloat() << std::endl;
	std::cout << "c * d = " << c << " * " << d << " = "<< c.toFloat() * d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d * a = " << d << " * " << a << " = "<< d.toFloat() * a.toFloat() << std::endl;
	std::cout << "d * b = " << d << " * " << b << " = "<< d.toFloat() * b.toFloat() << std::endl;
	std::cout << "d * c = " << d << " * " << c << " = "<< d.toFloat() * c.toFloat() << std::endl;
	std::cout << "d * d = " << d << " * " << d << " = "<< d.toFloat() * d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("/ overload opertation");
	std::cout << "a / a = " << a << " / " << a << " = "<< a.toFloat() / a.toFloat() << std::endl;
	std::cout << "a / b = " << a << " / " << b << " = "<< a.toFloat() / b.toFloat() << std::endl;
	std::cout << "a / c = " << a << " / " << c << " = "<< a.toFloat() / c.toFloat() << std::endl;
	std::cout << "a / d = " << a << " / " << d << " = "<< a.toFloat() / d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b / a = " << b << " / " << a << " = "<< b.toFloat() / a.toFloat() << std::endl;
	std::cout << "b / b = " << b << " / " << b << " = "<< b.toFloat() / b.toFloat() << std::endl;
	std::cout << "b / c = " << b << " / " << c << " = "<< b.toFloat() / c.toFloat() << std::endl;
	std::cout << "b / d = " << b << " / " << d << " = "<< b.toFloat() / d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c / a = " << c << " / " << a << " = "<< c.toFloat() / a.toFloat() << std::endl;
	std::cout << "c / b = " << c << " / " << b << " = "<< c.toFloat() / b.toFloat() << std::endl;
	std::cout << "c / c = " << c << " / " << c << " = "<< c.toFloat() / c.toFloat() << std::endl;
	std::cout << "c / d = " << c << " / " << d << " = "<< c.toFloat() / d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d / a = " << d << " / " << a << " = "<< d.toFloat() / a.toFloat() << std::endl;
	std::cout << "d / b = " << d << " / " << b << " = "<< d.toFloat() / b.toFloat() << std::endl;
	std::cout << "d / c = " << d << " / " << c << " = "<< d.toFloat() / c.toFloat() << std::endl;
	std::cout << "d / d = " << d << " / " << d << " = "<< d.toFloat() / d.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("< overload opertation");
	std::cout << "a < a = " << a << " < " << a << " = "<< (a.toFloat() < a.toFloat()) << std::endl;
	std::cout << "a < b = " << a << " < " << b << " = "<< (a.toFloat() < b.toFloat()) << std::endl;
	std::cout << "a < c = " << a << " < " << c << " = "<< (a.toFloat() < c.toFloat()) << std::endl;
	std::cout << "a < d = " << a << " < " << d << " = "<< (a.toFloat() < d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b < a = " << b << " < " << a << " = "<< (b.toFloat() < a.toFloat()) << std::endl;
	std::cout << "b < b = " << b << " < " << b << " = "<< (b.toFloat() < b.toFloat()) << std::endl;
	std::cout << "b < c = " << b << " < " << c << " = "<< (b.toFloat() < c.toFloat()) << std::endl;
	std::cout << "b < d = " << b << " < " << d << " = "<< (b.toFloat() < d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c < a = " << c << " < " << a << " = "<< (c.toFloat() < a.toFloat()) << std::endl;
	std::cout << "c < b = " << c << " < " << b << " = "<< (c.toFloat() < b.toFloat()) << std::endl;
	std::cout << "c < c = " << c << " < " << c << " = "<< (c.toFloat() < c.toFloat()) << std::endl;
	std::cout << "c < d = " << c << " < " << d << " = "<< (c.toFloat() < d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d < a = " << d << " < " << a << " = "<< (d.toFloat() < a.toFloat()) << std::endl;
	std::cout << "d < b = " << d << " < " << b << " = "<< (d.toFloat() < b.toFloat()) << std::endl;
	std::cout << "d < c = " << d << " < " << c << " = "<< (d.toFloat() < c.toFloat()) << std::endl;
	std::cout << "d < d = " << d << " < " << d << " = "<< (d.toFloat() < d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("> overload opertation");
	std::cout << "a > a = " << a << " > " << a << " = "<< (a.toFloat() > a.toFloat()) << std::endl;
	std::cout << "a > b = " << a << " > " << b << " = "<< (a.toFloat() > b.toFloat()) << std::endl;
	std::cout << "a > c = " << a << " > " << c << " = "<< (a.toFloat() > c.toFloat()) << std::endl;
	std::cout << "a > d = " << a << " > " << d << " = "<< (a.toFloat() > d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b > a = " << b << " > " << a << " = "<< (b.toFloat() > a.toFloat()) << std::endl;
	std::cout << "b > b = " << b << " > " << b << " = "<< (b.toFloat() > b.toFloat()) << std::endl;
	std::cout << "b > c = " << b << " > " << c << " = "<< (b.toFloat() > c.toFloat()) << std::endl;
	std::cout << "b > d = " << b << " > " << d << " = "<< (b.toFloat() > d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c > a = " << c << " > " << a << " = "<< (c.toFloat() > a.toFloat()) << std::endl;
	std::cout << "c > b = " << c << " > " << b << " = "<< (c.toFloat() > b.toFloat()) << std::endl;
	std::cout << "c > c = " << c << " > " << c << " = "<< (c.toFloat() > c.toFloat()) << std::endl;
	std::cout << "c > d = " << c << " > " << d << " = "<< (c.toFloat() > d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d > a = " << d << " > " << a << " = "<< (d.toFloat() > a.toFloat()) << std::endl;
	std::cout << "d > b = " << d << " > " << b << " = "<< (d.toFloat() > b.toFloat()) << std::endl;
	std::cout << "d > c = " << d << " > " << c << " = "<< (d.toFloat() > c.toFloat()) << std::endl;
	std::cout << "d > d = " << d << " > " << d << " = "<< (d.toFloat() > d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG(">= overload opertation");
	std::cout << "a >= a = " << a << " >= " << a << " = "<< (a.toFloat() >= a.toFloat()) << std::endl;
	std::cout << "a >= b = " << a << " >= " << b << " = "<< (a.toFloat() >= b.toFloat()) << std::endl;
	std::cout << "a >= c = " << a << " >= " << c << " = "<< (a.toFloat() >= c.toFloat()) << std::endl;
	std::cout << "a >= d = " << a << " >= " << d << " = "<< (a.toFloat() >= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b >= a = " << b << " >= " << a << " = "<< (b.toFloat() >= a.toFloat()) << std::endl;
	std::cout << "b >= b = " << b << " >= " << b << " = "<< (b.toFloat() >= b.toFloat()) << std::endl;
	std::cout << "b >= c = " << b << " >= " << c << " = "<< (b.toFloat() >= c.toFloat()) << std::endl;
	std::cout << "b >= d = " << b << " >= " << d << " = "<< (b.toFloat() >= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c >= a = " << c << " >= " << a << " = "<< (c.toFloat() >= a.toFloat()) << std::endl;
	std::cout << "c >= b = " << c << " >= " << b << " = "<< (c.toFloat() >= b.toFloat()) << std::endl;
	std::cout << "c >= c = " << c << " >= " << c << " = "<< (c.toFloat() >= c.toFloat()) << std::endl;
	std::cout << "c >= d = " << c << " >= " << d << " = "<< (c.toFloat() >= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d >= a = " << d << " >= " << a << " = "<< (d.toFloat() >= a.toFloat()) << std::endl;
	std::cout << "d >= b = " << d << " >= " << b << " = "<< (d.toFloat() >= b.toFloat()) << std::endl;
	std::cout << "d >= c = " << d << " >= " << c << " = "<< (d.toFloat() >= c.toFloat()) << std::endl;
	std::cout << "d >= d = " << d << " >= " << d << " = "<< (d.toFloat() >= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("<= overload opertation");
	std::cout << "a <= a = " << a << " <= " << a << " = "<< (a.toFloat() <= a.toFloat()) << std::endl;
	std::cout << "a <= b = " << a << " <= " << b << " = "<< (a.toFloat() <= b.toFloat()) << std::endl;
	std::cout << "a <= c = " << a << " <= " << c << " = "<< (a.toFloat() <= c.toFloat()) << std::endl;
	std::cout << "a <= d = " << a << " <= " << d << " = "<< (a.toFloat() <= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b <= a = " << b << " <= " << a << " = "<< (b.toFloat() <= a.toFloat()) << std::endl;
	std::cout << "b <= b = " << b << " <= " << b << " = "<< (b.toFloat() <= b.toFloat()) << std::endl;
	std::cout << "b <= c = " << b << " <= " << c << " = "<< (b.toFloat() <= c.toFloat()) << std::endl;
	std::cout << "b <= d = " << b << " <= " << d << " = "<< (b.toFloat() <= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c <= a = " << c << " <= " << a << " = "<< (c.toFloat() <= a.toFloat()) << std::endl;
	std::cout << "c <= b = " << c << " <= " << b << " = "<< (c.toFloat() <= b.toFloat()) << std::endl;
	std::cout << "c <= c = " << c << " <= " << c << " = "<< (c.toFloat() <= c.toFloat()) << std::endl;
	std::cout << "c <= d = " << c << " <= " << d << " = "<< (c.toFloat() <= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d <= a = " << d << " <= " << a << " = "<< (d.toFloat() <= a.toFloat()) << std::endl;
	std::cout << "d <= b = " << d << " <= " << b << " = "<< (d.toFloat() <= b.toFloat()) << std::endl;
	std::cout << "d <= c = " << d << " <= " << c << " = "<< (d.toFloat() <= c.toFloat()) << std::endl;
	std::cout << "d <= d = " << d << " <= " << d << " = "<< (d.toFloat() <= d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("== overload opertation");
	std::cout << "a == a = " << a << " == " << a << " = "<< (a.toFloat() == a.toFloat()) << std::endl;
	std::cout << "a == b = " << a << " == " << b << " = "<< (a.toFloat() == b.toFloat()) << std::endl;
	std::cout << "a == c = " << a << " == " << c << " = "<< (a.toFloat() == c.toFloat()) << std::endl;
	std::cout << "a == d = " << a << " == " << d << " = "<< (a.toFloat() == d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b == a = " << b << " == " << a << " = "<< (b.toFloat() == a.toFloat()) << std::endl;
	std::cout << "b == b = " << b << " == " << b << " = "<< (b.toFloat() == b.toFloat()) << std::endl;
	std::cout << "b == c = " << b << " == " << c << " = "<< (b.toFloat() == c.toFloat()) << std::endl;
	std::cout << "b == d = " << b << " == " << d << " = "<< (b.toFloat() == d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c == a = " << c << " == " << a << " = "<< (c.toFloat() == a.toFloat()) << std::endl;
	std::cout << "c == b = " << c << " == " << b << " = "<< (c.toFloat() == b.toFloat()) << std::endl;
	std::cout << "c == c = " << c << " == " << c << " = "<< (c.toFloat() == c.toFloat()) << std::endl;
	std::cout << "c == d = " << c << " == " << d << " = "<< (c.toFloat() == d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d == a = " << d << " == " << a << " = "<< (d.toFloat() == a.toFloat()) << std::endl;
	std::cout << "d == b = " << d << " == " << b << " = "<< (d.toFloat() == b.toFloat()) << std::endl;
	std::cout << "d == c = " << d << " == " << c << " = "<< (d.toFloat() == c.toFloat()) << std::endl;
	std::cout << "d == d = " << d << " == " << d << " = "<< (d.toFloat() == d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("!= overload opertation");
	std::cout << "a != a = " << a << " != " << a << " = "<< (a.toFloat() != a.toFloat()) << std::endl;
	std::cout << "a != b = " << a << " != " << b << " = "<< (a.toFloat() != b.toFloat()) << std::endl;
	std::cout << "a != c = " << a << " != " << c << " = "<< (a.toFloat() != c.toFloat()) << std::endl;
	std::cout << "a != d = " << a << " != " << d << " = "<< (a.toFloat() != d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "b != a = " << b << " != " << a << " = "<< (b.toFloat() != a.toFloat()) << std::endl;
	std::cout << "b != b = " << b << " != " << b << " = "<< (b.toFloat() != b.toFloat()) << std::endl;
	std::cout << "b != c = " << b << " != " << c << " = "<< (b.toFloat() != c.toFloat()) << std::endl;
	std::cout << "b != d = " << b << " != " << d << " = "<< (b.toFloat() != d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "c != a = " << c << " != " << a << " = "<< (c.toFloat() != a.toFloat()) << std::endl;
	std::cout << "c != b = " << c << " != " << b << " = "<< (c.toFloat() != b.toFloat()) << std::endl;
	std::cout << "c != c = " << c << " != " << c << " = "<< (c.toFloat() != c.toFloat()) << std::endl;
	std::cout << "c != d = " << c << " != " << d << " = "<< (c.toFloat() != d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << "d != a = " << d << " != " << a << " = "<< (d.toFloat() != a.toFloat()) << std::endl;
	std::cout << "d != b = " << d << " != " << b << " = "<< (d.toFloat() != b.toFloat()) << std::endl;
	std::cout << "d != c = " << d << " != " << c << " = "<< (d.toFloat() != c.toFloat()) << std::endl;
	std::cout << "d != d = " << d << " != " << d << " = "<< (d.toFloat() != d.toFloat()) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("min");
	std::cout << "min(a, a) = "<< Fixed::min( a, a ) << std::endl;
	std::cout << "min(a, b) = "<< Fixed::min( a, b ) << std::endl;
	std::cout << "min(a, c) = "<< Fixed::min( a, c ) << std::endl;
	std::cout << "min(a, d) = "<< Fixed::min( a, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "min(b, a) = "<< Fixed::min( b, a ) << std::endl;
	std::cout << "min(b, b) = "<< Fixed::min( b, b ) << std::endl;
	std::cout << "min(b, c) = "<< Fixed::min( b, c ) << std::endl;
	std::cout << "min(b, d) = "<< Fixed::min( b, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "min(c, a) = "<< Fixed::min( c, a ) << std::endl;
	std::cout << "min(c, b) = "<< Fixed::min( c, b ) << std::endl;
	std::cout << "min(c, c) = "<< Fixed::min( c, c ) << std::endl;
	std::cout << "min(c, d) = "<< Fixed::min( c, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "min(d, a) = "<< Fixed::min( d, a ) << std::endl;
	std::cout << "min(d, b) = "<< Fixed::min( d, b ) << std::endl;
	std::cout << "min(d, c) = "<< Fixed::min( d, c ) << std::endl;
	std::cout << "min(d, d) = "<< Fixed::min( d, d ) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("max");
	std::cout << "max(a, a) = "<< Fixed::max( a, a ) << std::endl;
	std::cout << "max(a, b) = "<< Fixed::max( a, b ) << std::endl;
	std::cout << "max(a, c) = "<< Fixed::max( a, c ) << std::endl;
	std::cout << "max(a, d) = "<< Fixed::max( a, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "max(b, a) = "<< Fixed::max( b, a ) << std::endl;
	std::cout << "max(b, b) = "<< Fixed::max( b, b ) << std::endl;
	std::cout << "max(b, c) = "<< Fixed::max( b, c ) << std::endl;
	std::cout << "max(b, d) = "<< Fixed::max( b, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "max(c, a) = "<< Fixed::max( c, a ) << std::endl;
	std::cout << "max(c, b) = "<< Fixed::max( c, b ) << std::endl;
	std::cout << "max(c, c) = "<< Fixed::max( c, c ) << std::endl;
	std::cout << "max(c, d) = "<< Fixed::max( c, d ) << std::endl;
	std::cout << std::endl;
	std::cout << "max(d, a) = "<< Fixed::max( d, a ) << std::endl;
	std::cout << "max(d, b) = "<< Fixed::max( d, b ) << std::endl;
	std::cout << "max(d, c) = "<< Fixed::max( d, c ) << std::endl;
	std::cout << "max(d, d) = "<< Fixed::max( d, d ) << std::endl;
	std::cout << std::endl;
	std::cout << std::endl;

	LOG("post-increment");
	std::cout << "a is " << a << " before post-increment" << std::endl;
	a++;
	std::cout << "a after post-increment " << a.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b is " << b << " before post-increment" << std::endl;
	b++;
	std::cout << "b after post-increment " << b.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c is " << c << " before post-increment" << std::endl;
	c++;
	std::cout << "c after post-increment " << c.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d is " << d << " before post-increment" << std::endl;
	d++;
	std::cout << "d after post-increment " << d.toFloat() << std::endl;

	std::cout << std::endl;
	std::cout << std::endl;

	LOG("pre-increment");
	std::cout << "a is " << a << " before pre-increment" << std::endl;
	++a;
	std::cout << "a after pre-increment " << a.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b is " << b << " before pre-increment" << std::endl;
	++b;
	std::cout << "b after pre-increment " << b.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c is " << c << " before pre-increment" << std::endl;
	++c;
	std::cout << "c after pre-increment " << c.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d is " << d << " before pre-increment" << std::endl;
	++d;
	std::cout << "d after pre-increment " << d.toFloat() << std::endl;

	std::cout << std::endl;
	std::cout << std::endl;

	LOG("post-decrement");
	std::cout << "a is " << a << " before post-decrement" << std::endl;
	a--;
	std::cout << "a after post-decrement " << a.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b is " << b << " before post-decrement" << std::endl;
	b--;
	std::cout << "b after post-decrement " << b.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c is " << c << " before post-decrement" << std::endl;
	c--;
	std::cout << "c after post-decrement " << c.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d is " << d << " before post-decrement" << std::endl;
	d--;
	std::cout << "d after post-decrement " << d.toFloat() << std::endl;

	std::cout << std::endl;
	std::cout << std::endl;

	LOG("pre-decrement");
	std::cout << "a is " << a << " before pre-decrement" << std::endl;
	--a;
	std::cout << "a after pre-decrement " << a.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "b is " << b << " before pre-decrement" << std::endl;
	--b;
	std::cout << "b after pre-decrement " << b.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "c is " << c << " before pre-decrement" << std::endl;
	--c;
	std::cout << "c after pre-decrement " << c.toFloat() << std::endl;
	std::cout << std::endl;
	std::cout << "d is " << d << " before pre-decrement" << std::endl;
	--d;
	std::cout << "d after pre-decrement " << d.toFloat() << std::endl;


	return 0;
}
